---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-server-data
  namespace: files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <STORAGE_CLASS>
  resources:
    requests:
      storage: <STORAGE_SIZE>
