{{- if .Values.service.enabled -}}
{{- if .Values.nexus.docker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" $ | trunc 49 }}-docker-5000
{{- if $.Values.service.annotations }}
  annotations:
{{ toYaml $.Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "nexus.labels" $ | nindent 4 }}
    {{- if $.Values.nexus.extraLabels }}
      {{- with $.Values.nexus.extraLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: docker-5000
  selector:
    {{- include "nexus.selectorLabels" $ | nindent 4 }}
    {{- if $.Values.nexus.extraSelectorLabels }}
      {{- with $.Values.nexus.extraSelectorLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}

{{- end }}
{{- end }}
