{{- define "lib-common.labels.standard" -}}
app: {{ template "app.name" . }}
chart: {{ template "app.chart" . }}
release: {{ .Release.Name | quote }}
{{- end -}}

{{- define "lib-common.labels.matchLabels" -}}
app: {{ template "app.name" . }}
release: {{ .Release.Name | quote }}
{{- end -}}
