{{- define "lib-common.serviceAccountName" -}}
{{- if .Values.rbac.create -}}
    {{ default (printf "%s" (include "app.fullname" .)) .Values.rbac.serviceAccountName }}
{{- else -}}
    {{ default "default" .Values.rbac.serviceAccountName }}
{{- end -}}
{{- end -}}

{{- define "lib-common.serviceAccount" -}}
{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lib-common.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "lib-common.labels.standard" . | nindent 4 }}
{{- end -}}
{{- end }}