---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-data
  namespace: ${IDO_TEAM}
  labels:
    velero.io/backup-app: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_NEXUS_STORAGE_SIZE}
