{{- define "app.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "app.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "app.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Usage:
{{ include "app.dependency.fullname" (list . "chartName") }}
*/}}
{{- define "app.dependency.fullname" -}}
{{- $top := first . -}}
{{- $depName := index . 1 -}}
{{- $depValues := (get $top.Values $depName) | default (dict) -}}
{{- if $depValues.fullnameOverride -}}
{{- $depValues.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default $depName $depValues.nameOverride -}}
{{- if contains $name $top.Release.Name -}}
{{- $top.Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" $top.Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Usage:
{{ include "app.component.fullname" . }}
*/}}
{{- define "app.component.fullname" -}}
{{- if .Component.Values.fullnameOverride -}}
{{- .Component.Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Component.Name .Component.Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "lib-common.name.fullname" -}}
{{- if .Component -}}
  {{- if .Component.Name -}}
    {{- include "app.component.fullname" . }}
  {{- else -}}
    {{- include "app.fullname" . }}
  {{- end -}}
{{- else -}}
  {{- include "app.fullname" . }}
{{- end -}}
{{- end -}}