---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-server-data
  namespace: ${IDO_TEAM}
  labels:
    velero.io/backup-app: fileserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_FILE_STORAGE_SIZE}