---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-server-data
  namespace: ${TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: ${FILE_STORAGE_SIZE}