---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-controller-data
  namespace: ${IDO_TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_JENKINS_CONTROLLER_STORAGE_SIZE}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-agent-data
  namespace: ${IDO_TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_JENKINS_AGENT_STORAGE_SIZE}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-lib-data
  namespace: ${IDO_TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: 5Gi