---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-controller-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <STORAGE_CLASS>
  resources:
    requests:
      storage: <CONTROLLER_STORAGE_SIZE>

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-agent-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <STORAGE_CLASS>
  resources:
    requests:
      storage: <AGENT_STORAGE_SIZE>
