{{- define "lib-common.configmap.file" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lib-common.name.fullname" .ctx }}-{{ .name }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
  namespace: {{ .ctx.Release.Namespace | quote }}
data:
  {{- range .opts.files }}
  {{ base . }}: |
  {{- tpl ($.ctx.Files.Get .) $.ctx | nindent 4 }}
  {{- end }}
{{- end }}

{{- define "lib-common.configmap.kv" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lib-common.name.fullname" .ctx }}-{{ .name }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
  namespace: {{ .ctx.Release.Namespace | quote }}
data:
  {{- if .opts.dataTpl }}
  {{ tpl ($.ctx.Files.Get .opts.dataTpl) $.ctx }}
  {{- else }}
  {{- range $k, $v := .opts.data }}
  {{ $k }}: {{ include "lib-common.utils.readRef" (dict "value" $v "ctx" $.ctx) | quote }}
  {{- end }}
  {{- end }}
{{- end }}

{{- define "lib-common.configmap.v2.tpl" -}}
{{- range $k, $opts := .values.configmaps }}
{{- if eq $opts.mode "file" }}
{{- include "lib-common.configmap.file" (dict "name" $k "opts" $opts "ctx" $.ctx) }}
{{- else if eq $opts.mode "kv" }}
{{- include "lib-common.configmap.kv" (dict "name" $k "opts" $opts "ctx" $.ctx) }}
{{- end }}
{{- end }}
{{- end }}

{{- define "lib-common.configmap.v2" -}}
{{- include "lib-common.values.merge" . -}}
{{- include "lib-common.configmap.v2.tpl" (dict "values" (default .Values .Component.Values) "ctx" .) -}}
{{- end -}}
