{{/*
Usage: include "lib-common.rbac.role" (dict "name" "" "rules" list "ctx" .)
*/}}
{{- define "lib-common.rbac.role" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ default (include "lib-common.name.fullname" .ctx) .name }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
rules: 
{{ toYaml .rules }}
{{- end }}

{{/*
Usage: include "lib-common.rbac.rolebinding" (dict "name" "" "roleName" "" "saName" "" "ctx" .)
*/}}
{{- define "lib-common.rbac.rolebinding" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default (include "lib-common.name.fullname" .ctx) .name }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .roleName }}
subjects:
- kind: ServiceAccount
  name: {{ .saName }}
{{- end }}

{{/*
Usage: {{- include "lib-common.rbac.v2.tpl" (dict "values" .Values "ctx" .) -}}
*/}}
{{- define "lib-common.rbac.v2.tpl" }}
{{- if .values.rbac.create }}
  {{- $name := include "lib-common.name.fullname" .ctx }}
  {{- if .values.rbac.role.rules }}
    {{- include "lib-common.rbac.role" (dict "name" $name "rules" .values.rbac.role.rules "ctx" .ctx) }}

    {{- $saName := include "lib-common.serviceAccountName.v2" (dict "values" .values "ctx" .ctx) }}
    {{- include "lib-common.rbac.rolebinding" (dict "roleName" $name "saName" $saName "ctx" .ctx) }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "lib-common.rbac.v2" -}}
{{- include "lib-common.values.merge" . -}}
{{- include "lib-common.rbac.v2.tpl" (dict "values" (default .Values .Component.Values) "ctx" .) -}}
{{- end -}}