{{- define "lib-common.secret.file" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lib-common.name.fullname" .ctx }}-{{ .name }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
  namespace: {{ .ctx.Release.Namespace | quote }}
data:
  {{- range .opts.files }}
  {{ base . }}: |
  {{- tpl ($.ctx.Files.Get .) $.ctx | b64enc | nindent 4 }}
  {{- end }}
{{- end }}

{{- define "lib-common.secret.kv" }}
{{- $name := printf "%s-%s" (include "lib-common.name.fullname" .ctx) .name }}
{{- $secret := (lookup "v1" "Secret" .ctx.Release.Namespace $name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
  {{- if .opts.labels }}
  {{- toYaml .opts.labels | nindent 4 }}
  {{- end }}
  {{- if .opts.annotations }}
  annotations: {{ toYaml .opts.annotations | nindent 4 }}
  {{- end }}
data:
  {{- if .opts.dataTpl }}
  {{ tpl ($.ctx.Files.Get .opts.dataTpl) $.ctx }}
  {{- else if and (empty .opts.data) $secret.data }}
  {{- toYaml $secret.data | nindent 2 }}
  {{- else }}
  {{- range $k, $v := .opts.data }}
  {{ $k }}: {{ include "lib-common.utils.readRef" (dict "value" $v "ctx" $.ctx) | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}

{{- define "lib-common.secrets.v2.tpl" -}}
{{- range $k, $opts := .values.secrets }}
{{- if eq $opts.mode "file" }}
{{- include "lib-common.secret.file" (dict "name" $k "opts" $opts "ctx" $.ctx) }}
{{- else if eq $opts.mode "kv" }}
{{- include "lib-common.secret.kv" (dict "name" $k "opts" $opts "ctx" $.ctx) }}
{{- end }}
{{- end }}
{{- end }}

{{- define "lib-common.secrets.v2" -}}
{{- include "lib-common.values.merge" . -}}
{{- include "lib-common.secrets.v2.tpl" (dict "values" (default .Values .Component.Values) "ctx" .) -}}
{{- end -}}
