{{/*
Usage: include "lib-common.serviceAccountName.v2" (dict "values" .Values "ctx" .)
Only support one service account for an chart now...
*/}}
{{- define "lib-common.serviceAccountName.v2" -}}
{{- if .values.rbac.create -}}
    {{ default (printf "%s" (include "lib-common.name.fullname" .ctx)) .values.rbac.serviceAccountName }}
{{- else -}}
    {{ default "default" .values.rbac.serviceAccountName }}
{{- end -}}
{{- end -}}


{{/*
Usage: include "lib-common.serviceAccount.v2.tpl" (dict "values" .Values "ctx" .)
Only support one service account for an chart now...
*/}}
{{- define "lib-common.serviceAccount.v2.tpl" -}}
{{- if .values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lib-common.serviceAccountName.v2" (dict "values" .values "ctx" .ctx) }}
  namespace: {{ .ctx.Release.Namespace | quote }}
  labels: {{- include "lib-common.labels.standard" .ctx | nindent 4 }}
{{- end -}}
{{- end }}

{{- define "lib-common.serviceAccount.v2" -}}
{{- include "lib-common.values.merge" . -}}
{{- include "lib-common.serviceAccount.v2.tpl" (dict "values" (default .Values .Component.Values) "ctx" .) -}}
{{- end -}}