---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zentao-data
  namespace: ${IDO_TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_ZENTAO_STORAGE_SIZE}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zentao-mysql-data
  namespace: ${IDO_TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_ZENTAO_DB_STORAGE_SIZE}