---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zentao-data
  namespace: ${TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: ${ZENTAO_STORAGE_SIZE}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zentao-mysql-data
  namespace: ${TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: ${ZENTAO_DB_STORAGE_SIZE}