replicas: 1
scalable: true

image:
  repository: app/zentao
  tag: "18.8"
  pullPolicy: Always

service:
  enabled: true
  type: ClusterIP

ports:
  - name: web
    protocol: tcp
    port: 80
  - name: probe
    protocol: tcp
    port: 80

probe:
  readiness:
    enabled: true
    type: http
    methods:
      http:
        httpGet:
          path: /check.html
          port: 80
  startup:
    enabled: true
    type: tcp
    methods:
      tcp:
        tcpSocket:
          port: 80

resources:
  cpu: 200m
  memory: 256Mi

oversold:
  cpu: 100m
  memory: 128Mi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "${FORCE_SSL_REDIRECT}"
    kubernetes.io/tls-acme: "${TLS_ACME}"
  host: "${CLUSTER_HOSTNAME}"
  paths:
  - path: ${ZENTAO_URL_PREFIX}
    port: 80
    type: Prefix
  tls:
    enabled: ${TLS_ENABLED}
    secretName: ${TLS_SECRET}
    host: ${TLS_HOST}

env:
  ZT_MYSQL_PASSWORD:
    source: secret
    key: mysql_password
    subChartRefs:
    - when: mysql.enabled
      name: mysql
  ZT_MYSQL_DB: "$ref:mysql.auth.database"
  ZT_MYSQL_PORT: "$ref:mysql.auth.port"
  ZT_MYSQL_USER: "$ref:mysql.auth.user"
  IS_CONTAINER: "true"
  SMTP_ENABLED: '$ref:mail.enabled'
  SMTP_FROMNAME: "ZenTao"
  APP_DOMAIN: "${DOMAIN}"
  APP_WEB_ROOT: "${ZENTAO_URL_PREFIX}"

mysql:
  enabled: true
  auth:
    rootPassword: pass4zenTao
    user: "root"
    password: "pass4zenTao"
    database: "zentao"
    port: 3306
  volumes:
    data:
      existingClaim: zentao-mysql-data
  podSecurityContext:
    fsGroup: 1001
    fsGroupChangePolicy: "OnRootMismatch"

secret:
  data:
    mysql_password:
      value: "$ref:mysql.auth.password"
      length: 20
      allowOverride: true

mail:
  enabled: false
  smtp: {}

configmaps:
  mail:
    mode: kv
    data:
      SMTP_HOST: '$ref:mail.smtp.host'
      SMTP_PORT: '$ref:mail.smtp.port'
      SMTP_USER: '$ref:mail.smtp.user'
      SMTP_PASS: '$ref:mail.smtp.pass'

envFrom:
  configmaps:
   - mail

db:
  config:
    grant_super_privilege: "true"

global:
  allowOverSold: true
  cleanPolicy:
    workflow: true
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: vm-agent
                operator: NotIn
                values:
                  - 'True'

volumes:
  data:
    existingClaim: zentao-data
    type: pvc
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    mounts:
    - mountPath: /data
      subPath: ""

command:
  - /bin/sh
  - -c
  - |
    if [ ! -e "/apps/zentao/module/install/view/step3.html.php.original" ]; then
      cp /apps/zentao/module/install/view/step3.html.php /apps/zentao/module/install/view/step3.html.php.original
      sed -i -e "s/^\([[:blank:]]*\)\(\$configContent[[:blank:]]*=[[:blank:]]*<<<EOT\)/\1\$webRoot = getenv\('APP_WEB_ROOT'\) \. '\/';\n\1\2/" \
        -e "s/\(config->webRoot[[:blank:]]*=[[:blank:]]*\)getWebRoot();/\1'\$webRoot';/" \
        /apps/zentao/module/install/view/step3.html.php
    fi
    /usr/bin/entrypoint.sh