---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
  namespace: ${IDO_TEAM}
  labels:
    velero.io/backup-app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_SONAR_STORAGE_SIZE}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-pg-data
  namespace: ${IDO_TEAM}
  labels:
    velero.io/backup-app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${IDO_STORAGE_CLASS}
  resources:
    requests:
      storage: ${IDO_SONAR_PG_STORAGE_SIZE}