---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
  namespace: ${TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: ${SONAR_STORAGE_SIZE}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-pg-data
  namespace: ${TEAM}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: ${SONAR_PG_STORAGE_SIZE}